import torch
import glob
import os
import numpy as np

def main():
    tasks = ['PVT', 'NBACK', 'FLANKER', 'MATB']
    
    # Ensure Flex-MoE's raw_data folder exists
    save_dir = '/content/Flex-MoE-COGBCI/raw_data/'
    os.makedirs(save_dir, exist_ok=True)

    for task_name in tasks:
        print(f"\n🔄 Stacking dictionaries for {task_name}...")
        
        # FIX: Point to the local processed_data folder generated by dataset.py
        data_dir = f'./processed_data/{task_name}/**/*.pt'
        all_tensor_files = glob.glob(data_dir, recursive=True)
        
        if len(all_tensor_files) == 0:
            # Fallback for flat directory structure
            data_dir_flat = f'./processed_data/{task_name}/*.pt'
            all_tensor_files = glob.glob(data_dir_flat)

        print(f"   Found {len(all_tensor_files)} total windows for {task_name}.")

        if len(all_tensor_files) == 0:
            print(f"   ⚠️ Skipping {task_name} (No data found).")
            continue

        all_data, all_labels = [], []

        for file_path in all_tensor_files:
            filename = os.path.basename(file_path)
            try:
                # Extract binary label (0 for Low, 1 for High)
                label_str = filename.split('_')[-2] 
                all_labels.append(int(label_str))
            except ValueError:
                continue 
            
            obj = torch.load(file_path)
            if isinstance(obj, dict):
                for val in obj.values():
                    if isinstance(val, (torch.Tensor, np.ndarray)):
                        tensor = val
                        break
            else: tensor = obj
                
            if isinstance(tensor, np.ndarray): tensor = torch.tensor(tensor)
            all_data.append(tensor.float())

        if len(all_data) == 0:
            print(f"   ⚠️ Could not extract valid tensors for {task_name}.")
            continue

        # Stack into [Batch, 750, 9]
        master_data = torch.stack(all_data)
        master_labels = torch.tensor(all_labels)

        # Save straight to raw_data
        torch.save(master_data, os.path.join(save_dir, f'cogbci_data_{task_name}.pt'))
        torch.save(master_labels, os.path.join(save_dir, f'cogbci_labels_{task_name}.pt'))
        print(f"   ✅ Saved {task_name} | Data: {master_data.shape}")

if __name__ == "__main__":
    main()
